x-base: &base
  mem_reservation: 256m
  mem_limit: 512m
  cpus: '0.5'

  restart: unless-stopped

  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"

x-healthcheck: &healthcheck
  retries: 3
  timeout: 3s
  interval: 3s
  start_period: 3s 
  start_interval: 3s

# ---

services:
  currency:
    <<: *base
    image: ${CMD_NAME:-microservices-currency}:latest
    container_name: ${CMD_NAME:-microservices-currency}

    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_NAME: ${CMD_NAME:-microservices-currency}
        APP_PORT: ${APP_PORT:-50052}
        GO_VERSION: ${GO_VERSION:-1.25.0}

    ports:
      - ${HOST_PORT:-50052}:${APP_PORT:-50052}

    networks:
      - app
      - data

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${APP_PORT:-50052} || exit 1"]
      <<: *healthcheck

    depends_on:
      currency-postgres:
        condition: service_healthy
      currency-postgres-migrate:
        condition: service_completed_successfully

    env_file: [".env"]
