x-base: &base
  mem_reservation: 256m
  mem_limit: 512m
  cpus: '0.5'

  restart: unless-stopped

  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"

x-healthcheck: &healthcheck
  retries: 3
  timeout: 3s
  interval: 3s
  start_period: 30s
  start_interval: 3s

# ---

services:
  currency-postgres:
    <<: *base
    image: postgres:latest
    container_name: ${CMD_NAME:-microservices-currency}-postgres

    volumes:
      - currency:/var/lib/postgresql/data

    networks:
      - data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-currency} -h localhost"]
      <<: *healthcheck

    env_file: [".env"]

  currency-postgres-migrate:
    image: migrate/migrate:latest    
    command: ["-path=/migrations", "-database=${POSTGRES_DSN}", "up"]

    volumes:
      - ./migrations:/migrations

    networks:
      - data

    depends_on:
      currency-postgres:
        condition: service_healthy

    env_file: [".env"]
